### ISSUE TITLE
How to generate depth?

### ISSUE THREAD

**Issue by volcverse** [lehduong/OneDiffusion#11]
Hello, thanks for sharing the great work.

I'm wondering how to generate depth map and human pose. I tried prompt like [[image2depth]] but the results are still natural images rather than depth or pose.

**Comment by lehduong** [comment]
Apologies for the confusion. For image-to-condition tasks, use the same task token as the corresponding condition-to-image task (which is `[[depth2image]]` and `[[pose2image]]` in this case). However, you need to set the `denoise_mask` argument in the `img2img` function of the pipeline to `[0, 1]`. This can be configured in the Gradio demo as in below images (uncheck `image_0` and check `image_1`). 

![Screenshot 2024-12-12 at 12 50 05 AM](https://github.com/user-attachments/assets/b4287906-0ce1-450c-a33b-3ae0866e8001)
![Screenshot 2024-12-12 at 12 50 14 AM](https://github.com/user-attachments/assets/8b7b82ea-788c-444d-825b-e352cfe44757)

This is because the first view is always an RGB image, while the second view is set to the condition (e.g., depth, HED, pose, etc.) during training. Denoise mask [0, 1] means we want to set the input (which is a RGB image in this case) to the first view and generate the second view.

**Comment by volcverse** [comment]
Thank you for your timely response!
